# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shuffle Grand Prix
description: "Shuffle Grand Prix is a fast-paced futuristic hover-bike racing game! Race for glory across randomly generated tracks in a wide variety of environments. Share your favorite randomly generated tracks with friends and foes."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shufflegrandprix.com" # the base hostname & protocol for your site
paginate: 5
paginate_path: "blog/page:num"
excerpt_separator: "<!--break-->"

# Build settings
gems: [jekyll-paginate]
markdown: redcarpet

# Content settings
blog_feed_url: "http://coinflipgamesllc.github.io/feed.shuffle-grand-prix.xml"

email: hi@coinflipgames.co
twitter_username: coinflipgames
facebook_username: coinflipgames
indiedb_username: coinflipgames
youtube_username: coinflipgames
